# Dependabot configuration for automatic dependency updates
version: 2
updates:
  # NPM
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps):"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    groups:
      npm-all-updates:
        patterns:
          - "*"
        update-types:
          - "major"
          - "minor"
          - "patch"
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps): actions update"
    labels:
      - "dependencies"
      - "github-actions"
